definitions:
  common.BasicResponse:
    properties:
      message:
        type: string
      status:
        type: string
      statusCode:
        type: integer
    type: object
  common.ErrorResponse:
    properties:
      message:
        type: string
      need_retry:
        type: boolean
      retry_reason:
        type: string
      status:
        type: string
      statusCode:
        type: integer
    type: object
  schema.LoginRequest:
    properties:
      otp:
        type: string
      phone_number:
        type: string
    required:
    - otp
    - phone_number
    type: object
  schema.OTPRequest:
    properties:
      phone_number:
        type: string
    required:
    - phone_number
    type: object
  schema.User:
    properties:
      id:
        type: integer
      phone_number:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/request:
    post:
      consumes:
      - application/json
      description: Requests an OTP to be sent to the given phone number.
      parameters:
      - description: Phone number for OTP
        in: body
        name: OTPRequest
        required: true
        schema:
          $ref: '#/definitions/schema.OTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OTP sent successfully
          schema:
            $ref: '#/definitions/common.BasicResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "429":
          description: Too many OTP requests
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Request OTP
      tags:
      - Auth
  /api/v1/auth/verify:
    post:
      consumes:
      - application/json
      description: Verifies the OTP code for the given phone number and returns an
        access token.
      parameters:
      - description: Phone number and OTP code
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/schema.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OTP verified successfully
          schema:
            $ref: '#/definitions/common.BasicResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "401":
          description: Incorrect OTP code or verification failed
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "404":
          description: OTP not found or expired
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Verify OTP
      tags:
      - Auth
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: Retrieves a paginated list of users, with optional phone number
        search.
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of users per page
        in: query
        name: page_size
        type: integer
      - description: Filter by phone number
        in: query
        name: phone_number
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schema.User'
            type: array
      summary: List users
      tags:
      - Users
  /api/v1/users/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a user by their unique ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: returns the user details including the id and phone number
          schema:
            $ref: '#/definitions/schema.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.ErrorResponse'
      summary: Get user by ID
      tags:
      - Users
swagger: "2.0"
